"use client";
import './globals.css';
import { useState } from 'react';
import { Inter } from 'next/font/google'
import Sidebar from "./components/sidebar";
import Navbar from './components/navbar';
const inter = Inter({ subsets: ['latin'] });
import { StateContext } from "@/app/components/displayedItem";

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  const [displayedItemId, setDisplayedItemId] = useState<number | null>(null);
  return (
    <StateContext.Provider value={{ displayedItemId, setDisplayedItemId }}>
    <html lang="en">
      <body suppressHydrationWarning={true}>
      <div className='bg-[radial-gradient(circle_at_bottom_right,_var(--tw-gradient-stops))] from-secondary via-[#154D61] to-primary to-60% '>
        <Navbar />
        <div>
          {children}
        </div> 
      </div>
      </body>
    </html>
    </StateContext.Provider>
  )
}
