"use client";
import './globals.css';
import { useState } from 'react';
import { Inter } from 'next/font/google'
import Sidebar from "./components/sidebar";
import Navbar from './components/navbar';
const inter = Inter({ subsets: ['latin'] });
import { StateContext } from "@/app/components/displayedItem";

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  const [displayedItemId, setDisplayedItemId] = useState<number | null>(null);
  return (
    <StateContext.Provider value={{ displayedItemId, setDisplayedItemId }}>
    <html lang="en">
      <body suppressHydrationWarning={true}>
      <div>
        <Navbar />
        <div className="grid grid-cols-4 bg-primary">
          <div className='col-span-1 border-r border-secondary'><Sidebar /></div>
          <div className='col-span-3'>{children}</div>
        </div>
        <div>footer</div>  
      </div>
      </body>
    </html>
    </StateContext.Provider>
  )
}
